name: action

on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Git clone 
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Original test"
          ls -la 
       
          echo "Build success"
