
name: action

on:
  [ pull_request_target ]

jobs:
  
  prep:
    runs-on: self-hosted
    steps:
      - name: Git clone 
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: resources/
          
      - name: Build
        run: |
          cp /home/github_actions/scripts/check_files.sh ./resources/
          ./resources/check_files.sh
          cp /home/github_actions/scripts/check_user.sh ./resources/
          ./resources/check_user.sh
  
  test:
    runs-on: self-hosted
    needs: prep
    steps:
      - name: Checking
        run: |  
          bash /home/github_actions/scripts/build_fast.sh
          bash /home/github_actions/scripts/build_full.sh
  
  send_log:
    runs-on: self-hosted
    needs: [test]
    if: always() && (needs.test.result == 'failure')
    steps: 
      - name: Send_log
        run: |
          /home/github_actions/scripts/send_log.sh
          echo "Check your email"
  clear_all:
    runs-on: self-hosted
    needs: [prep, test, send_log]
    if: always()
    steps: 
      - name: Clear
        run: |
          /home/github_actions/scripts/clear_all.sh
        
