
name: action

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ testeous ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Git clone 
        uses: actions/checkout@v2
      - name: Build
        run: |
          ls -la
          echo "My test"
          echo "Bad mgs"
          echo "I will crush YOU!!"  
          mv rtl/ /home/github_actions/cordic_runner/cordic_verif
          cd /home/github_actions/cordic_runner/cordic_verif
          echo  ${{github.event.pull_request.head.email}} > email
          echo ${{github.actor}} > name
          ./start.sh
          echo "Build success"
